name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > types.ts
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Report test results
        if: always()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ACTIONS_STATUS_CHECK_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { eventName, sha, runId } = context;
            const run = await github.rest.actions.getWorkflowRun({ owner, repo, run_id: runId });

            const status = run.data.conclusion === 'success' ? 'success' : 'failure';
            const target_url = `https://github.com/${owner}/${repo}/actions/runs/${runId}`;

            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: status,
              target_url,
              description: 'CI tests passed.',
              context: 'CI',
            });
