name: Deploy Migrations to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      PRODUCTION_PROJECT_ID: pbtxcelbykjcjukklxqk

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          supabase link --project-ref $PRODUCTION_PROJECT_ID
          supabase db push

      - name: Report test results
        if: always()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ACTIONS_STATUS_CHECK_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { eventName, sha, runId } = context;
            const { conclusion } = await github.rest.checks.getSuite({ owner, repo, check_suite_id: runId });

            const status = conclusion === 'success' ? 'success' : 'failure';
            const target_url = `https://github.com/${owner}/${repo}/actions/runs/${runId}`;

            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: status,
              target_url,
              description: 'Migrations deployed to production.',
              context: 'Deploy Migrations',
            });
